#!/bin/bash

# ==== STATA COMMAND ====
# # Set your Stata command here (adjust for your model and install location)
STATA_CMD="/Applications/Stata/StataIC.app/Contents/MacOS/StataIC"
export STATA_CMD

echo "User profile setup completed."
